/**
 * Sticker art — GENERATED by tools/gen-stickers.py. Do not edit by hand.
 *
 * 32 accessories in six slots. The slot is what lets "surprise me" put hats
 * on heads and bags at the duck's side rather than scattering things at
 * random, and it gives keyboard placement a sensible starting position.
 *
 * `ax`/`ay` is the cell inside the sprite that lands on the tap point.
 */

export type SlotName = "hat" | "face" | "neck" | "body" | "held" | "float";

export interface StickerDef {
  slot: SlotName;
  rows: string[];
  ax: number;
  ay: number;
  name: string;
}

export const STICKER_PALETTE = {
  k: "#2B2B24", w: "#FFFFFF", r: "#FF4B4B", y: "#FFCA00", b: "#3FB5D8",
  g: "#5AD08A", p: "#FF6FA5", o: "#FF8953", n: "#8B5E34", s: "#C9D6DC",
} as const;

export const STICKERS: Record<string, StickerDef> = {

  tophat: { slot: "hat", ax: 3, ay: 3, name: "Top hat",
    rows: [".kkkkk.", ".kkkkk.", ".rrrrr.", "kkkkkkk"] },
  cap: { slot: "hat", ax: 3, ay: 3, name: "Cap",
    rows: ["..bbbb..", ".bbbbbb.", "bbbbbbbb", ".....bbb"] },
  beanie: { slot: "hat", ax: 3, ay: 3, name: "Beanie",
    rows: ["..gg..", ".gggg.", "gggggg", "wwwwww"] },
  cowboy: { slot: "hat", ax: 4, ay: 3, name: "Cowboy hat",
    rows: ["...nnn...", "..nnnnn..", ".nnnnnnn.", "nnnnnnnnn"] },
  crown: { slot: "hat", ax: 3, ay: 2, name: "Crown",
    rows: ["y.y.y.y", "yyyyyyy", ".yyyyy."] },
  party: { slot: "hat", ax: 2, ay: 4, name: "Party hat",
    rows: ["..w..", "..p..", ".ppp.", ".ppp.", "ppppp"] },
  wizard: { slot: "hat", ax: 3, ay: 5, name: "Wizard hat",
    rows: ["...y...", "...b...", "..bbb..", "..bbb..", ".bbbbb.", "bbbbbbb"] },
  wreath: { slot: "hat", ax: 3, ay: 1, name: "Flower crown",
    rows: ["p.y.p.y", "ggggggg"] },
  halo: { slot: "hat", ax: 2, ay: 1, name: "Halo",
    rows: [".yyyy.", "y....y"] },
  bow: { slot: "hat", ax: 3, ay: 1, name: "Hair bow",
    rows: ["pp...pp", "pppwppp", "pp...pp"] },
  shades: { slot: "face", ax: 1, ay: 0, name: "Sunglasses",
    rows: ["kkkkk", ".kkk."] },
  specs: { slot: "face", ax: 1, ay: 1, name: "Glasses",
    rows: ["ssss", "s..s", "ssss"] },
  patch: { slot: "face", ax: 1, ay: 0, name: "Eyepatch",
    rows: ["kkkk", ".kk."] },
  blush: { slot: "face", ax: 1, ay: 0, name: "Blush",
    rows: ["ppp", ".p."] },
  tache: { slot: "face", ax: 2, ay: 0, name: "Moustache",
    rows: ["nn.nn", ".n.n."] },
  scarf: { slot: "neck", ax: 3, ay: 0, name: "Scarf",
    rows: ["rrrrrrr", "rrrrrrr", "..rr...", "..rr..."] },
  bowtie: { slot: "neck", ax: 2, ay: 1, name: "Bow tie",
    rows: ["rr.rr", "rrwrr", "rr.rr"] },
  chain: { slot: "neck", ax: 2, ay: 0, name: "Chain",
    rows: ["ssssss", "..yy.."] },
  collar: { slot: "neck", ax: 2, ay: 0, name: "Collar",
    rows: ["wwwwww", ".w..w."] },
  heart: { slot: "body", ax: 3, ay: 2, name: "Heart",
    rows: [".rr.rr.", "rrrrrrr", "rrrrrrr", ".rrrrr.", "..rrr..", "...r..."] },
  star: { slot: "body", ax: 2, ay: 1, name: "Star",
    rows: ["..y..", "yyyyy", ".yyy.", "y...y"] },
  spot: { slot: "body", ax: 1, ay: 1, name: "Spot",
    rows: [".nn.", "nnnn", "nnnn", ".nn."] },
  stripe: { slot: "body", ax: 2, ay: 1, name: "Stripes",
    rows: ["wwwwww", "......", "wwwwww"] },
  pocket: { slot: "body", ax: 1, ay: 1, name: "Pocket",
    rows: ["bbbb", "b..b", "bbbb"] },
  handbag: { slot: "held", ax: 2, ay: 4, name: "Handbag",
    rows: ["..s..", ".s.s.", "nnnnn", "nyyyn", "nnnnn"] },
  tote: { slot: "held", ax: 2, ay: 4, name: "Tote bag",
    rows: ["s...s", "s...s", "ppppp", "ppppp", "ppppp"] },
  basket: { slot: "held", ax: 2, ay: 4, name: "Basket",
    rows: ["..s..", ".s.s.", "nwnwn", "wnwnw", "nwnwn"] },
  satchel: { slot: "held", ax: 2, ay: 4, name: "Satchel",
    rows: ["sssss", "n...n", "nnnnn", "nyynn", "nnnnn"] },
  balloon: { slot: "float", ax: 2, ay: 6, name: "Balloon",
    rows: [".rrr.", "rrrrr", "rrrrr", ".rrr.", "..r..", "..s..", "..s.."] },
  fish: { slot: "float", ax: 1, ay: 1, name: "Fish",
    rows: [".oo.", "oooo", ".oo."] },
  leaf: { slot: "float", ax: 1, ay: 1, name: "Leaf",
    rows: [".gg", "ggg", "gg."] },
  spark: { slot: "float", ax: 1, ay: 1, name: "Sparkle",
    rows: [".y.", "yyy", ".y."] },
};

/** Where a sticker lands by default: hats on the head, bags at the side. */
export const SLOT_ORIGIN: Record<SlotName, [number, number]> = {
  hat: [15, 2],
  face: [15, 5],
  neck: [13, 10],
  body: [10, 15],
  held: [7, 13],
  float: [5, 7],
};

export const SLOT_LABELS: Record<SlotName, string> = {
  hat: "Hats", face: "Face", neck: "Neck",
  body: "Body", held: "Bags", float: "Extras",
};

/** Six is the cap. They may overlap freely — that's part of the fun. */
export const MAX_STICKERS = 6;
