// ABOUTME: Routes Pond page and API requests across sessions, fortune entries, and administration.
// ABOUTME: Exchanges signed NFC URLs for private visitor sessions and personal pond data.

/**
 * The Pond — the API router.
 *
 * Platform-agnostic on purpose: `handle(req, env)` takes a web `Request` and
 * returns a web `Response`, and knows nothing about Vercel. `api/` holds the
 * three-line files that hand it one. That is what made the move off
 * Cloudflare a day's work instead of a rewrite, and it is what would make
 * the next move the same.
 *
 * Two things are worth reading before changing anything here:
 *
 *  1. `?d=` is checked exactly once (see session.ts) and never again.
 *  2. `?d=` is also FORGEABLE — anyone can type /?d=1. It proves a fortune
 *     was requested, not that a coin was inserted. Everything that could be
 *     abused because of that is rate-limited per card and per visitor (see
 *     limits.ts), and the honest threat model is in docs/pond/SECURITY.md.
 *
 * Served from ducky.davidyang.work — its own subdomain, because the apex
 * davidyang.work stays on Cargo.
 */

import type { DuckInput } from "./ducks.js";
import {
  deleteDuck, duckByEditKey, duckBySlug, listPond, renameDuck,
  topBumpers, updateDuck, validateDuck, validateScope,
} from "./ducks.js";
import { withdrawContact } from "./contact.js";
import {
  adminDucks, adminState, attachDuck, authorised, contactsCsv, deleteCard,
  deleteCardDucks, deleteDuckAsAdmin, markContact, resetKeeper, resolveReports,
  setCardDisabled, setCardLabel, setHidden, setKeeper, signIn, unlinkDucks,
} from "./admin.js";
import {
  claimCard, claimFromSession, endTenure, ensureCard, epochForEditKey,
  keeperOffer, keeperState, linkClaimerDuck, saveKeeper,
} from "./keeper.js";
import { createDuck, setContact } from "./release.js";
import { normaliseSlug, slugTaken } from "./slug.js";
import { bump, extinguish, report, say } from "./social.js";
import { keeperNameOfCard } from "./keeper.js";
import { loadSession, mintSession, readSessionCookie, sweep, visitorHash } from "./session.js";
import type { Env } from "./types.js";
import { badRequest, cleanText, intParam, json, notFound, nowSec, randomId, safeToken } from "./util.js";

const VISITOR_COOKIE = "pond_v";

/** Internal duck ids, as generated by randomId(10). */
const DUCK_ID = /^[A-Za-z0-9]{6,16}$/;

/** Applied to every response. */
export function securityHeaders(extra?: HeadersInit): Headers {
  const h = new Headers(extra);
  h.set("x-content-type-options", "nosniff");
  h.set("x-frame-options", "DENY");
  // The edit link IS the credential, so it must never travel in a Referer
  // header to anything a duck's message happens to link to.
  h.set("referrer-policy", "no-referrer");
  h.set(
    "content-security-policy",
    "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; " +
      "script-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'self'; " +
      "frame-ancestors 'none'",
  );
  return h;
}

/**
 * A stable-per-browser id used only to count rescues and reports once per
 * person, and to rate-limit minting. Not an IP, not a fingerprint; if it's
 * cleared, the worst that happens is someone gets a fresh allowance.
 */
export async function ensureVisitor(
  req: Request,
  env: Env,
): Promise<{ visitor: string; setCookie: string | null }> {
  const cookies = req.headers.get("cookie") ?? "";
  const match = cookies.match(/(?:^|;\s*)pond_v=([A-Za-z0-9]{8,64})/);
  if (match?.[1]) return { visitor: await visitorHash(env, match[1]), setCookie: null };

  const raw = randomId(24);
  const setCookie = [
    `${VISITOR_COOKIE}=${raw}`,
    "Path=/",
    "HttpOnly",
    "Secure",
    "SameSite=Lax",
    "Max-Age=31536000",
  ].join("; ");
  return { visitor: await visitorHash(env, raw), setCookie };
}

async function readJson(req: Request): Promise<Record<string, unknown> | null> {
  if (!req.headers.get("content-type")?.includes("application/json")) return null;
  // A public write endpoint should not accept an unbounded body.
  const text = await req.text();
  if (text.length > 4096) return null;
  try {
    const parsed = JSON.parse(text);
    return typeof parsed === "object" && parsed !== null ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Exchange a fresh `?d=` for a session, if there is one to exchange.
 *
 * Lives here rather than in the shell renderer because both the pond page
 * and any future entry point need identical behaviour, and because getting
 * this wrong in one place only would be invisible until someone's duck
 * died on the submit button.
 */
export async function mintFromQuery(
  req: Request,
  env: Env,
  url: URL,
  visitor: string,
  /*
   * Two answers, because the page needs both and only this function is in
   * a position to give them. `cookie` is the session, if one was minted.
   * `card` is the serial ONCE ITS SIGNATURE HAS BEEN CHECKED, and null
   * otherwise — so a caller cannot accidentally use the unchecked one, as
   * `pondPage` was doing when it picked the page's language.
   */
): Promise<{ cookie: string | null; card: string | null }> {
  /*
   * ══ THE CARD REGISTERS ITSELF ══
   * Before anything else, and regardless of whether there is a fortune to
   * mint. A tap carrying a valid signature is a real card saying hello,
   * and that is the only introduction the pond needs — no CSV, no import
   * step, nothing to keep in step by hand.
   *
   * It runs even for `?d=0`, a card whose fortune window has closed,
   * because the card is no less real for having gone quiet.
   */
  const claimed = safeToken(url.searchParams.get("c"), 12);
  const real = await ensureCard(
    env,
    claimed,
    url.searchParams.get("g"),
    url.searchParams.get("t"),
  );

  // Verified or not, this is the only card this request will admit to.
  const card = real ? claimed : null;

  const digit = intParam(url.searchParams.get("d"), 0, 4);
  if (!digit || digit < 1) return { cookie: null, card };

  // Preserve an unfinished fortune, but let a completed tap accrue another
  // entry in this visitor's pond.
  const existing = await readSessionCookie(env, req);
  const held = existing ? await loadSession(env, existing) : null;
  if (held && !held.spentDuck) return { cookie: null, card };

  const minted = await mintSession(env, {
    digit,
    /*
     * ══ THE SERIAL IS A CLAIM UNTIL THE SIGNATURE AGREES ══
     * `ensureCard` answers exactly one question — was this a real card
     * saying hello — and its answer used to be thrown away, while the
     * serial went into the session straight from the query string. So a
     * session could be bound to a card nobody had touched, by anybody who
     * had once seen that card's URL.
     *
     * That was survivable while `mintSession` was the only thing reading
     * it: it refuses a serial absent from `cards`, so the worst outcome
     * was a duck attributed to a card that does exist. It stops being
     * survivable the moment a session can CLAIM a card (docs/pond/
     * KEEPER.md § 6). Keepership would go to whoever typed a serial,
     * which is the precise thing the signature scheme exists to prevent.
     *
     * Requiring the signature costs nothing real, because there is no
     * such thing as a genuine tap without one: `&c=`, `&g=` and `&t=` are
     * all written at provisioning and only the fortune digit is ever
     * patched (firmware config.h, the NDEF layout).
     *
     * A card flashed with the placeholder all-zero key therefore never
     * verifies, and its ducks carry no provenance at all. That is the
     * intended reading rather than a regression — such a card's token is
     * forgeable by anyone, so attributing anything to it was always a
     * fiction — but it does mean the fix is to reflash and erase, never a
     * row edit. See KEEPER.md § 6.
     */
    cardId: card,
    nonce: safeToken(url.searchParams.get("n"), 32),
    visitor,
  });
  return { cookie: minted ? minted.cookie : null, card };
}

/**
 * Everything under /api.
 *
 * `pathname` is passed in rather than read off the request, because on
 * Vercel `/api/*` arrives through a rewrite and a rewritten request carries
 * its DESTINATION path, not the one the visitor typed. `api/router.ts`
 * reassembles the real one and hands it over; nothing in this file needs to
 * know that happened, which is the point of the split.
 *
 * It falls back to `req.url` so that tests, and any platform that routes by
 * path natively, can call this with two arguments and get the obvious
 * behaviour.
 */
export async function handle(req: Request, env: Env, pathname?: string): Promise<Response> {
  const url = new URL(req.url);
  const path = (pathname ?? url.pathname).replace(/\/+$/, "") || "/";

  const { visitor, setCookie } = await ensureVisitor(req, env);
  const headers = securityHeaders();
  if (setCookie) headers.append("set-cookie", setCookie);

  // ── the pond ────────────────────────────────────────────────────────────
  if (path === "/api/pond" && req.method === "GET") {
    const ducks = await listPond(env, visitor);
    return json({ ducks, now: nowSec() }, { headers });
  }

  if (path === "/api/bumpers" && req.method === "GET") {
    // Read-only and public, like the pond itself — it returns pictures of
    // ducks that are already on screen, and no names.
    const duck = url.searchParams.get("duck") ?? "";
    if (!/^[A-Za-z0-9]{6,32}$/.test(duck)) return notFound(headers);
    return json({ bumpers: await topBumpers(env, duck) }, { headers });
  }

  if (path === "/api/session" && req.method === "GET") {
    const id = await readSessionCookie(env, req);
    const s = id ? await loadSession(env, id) : null;
    return json(
      s
        ? {
            active: true,
            fortune: s.fortune,
            spent: Boolean(s.spentDuck),
            // Decides whether the contact screen may offer to share with
            // the keeper. It must name them, so it needs the name.
            keeper: await keeperNameOfCard(env, s.cardId),
            /*
             * Whether to offer this person the card. Answered here rather
             * than inferred by the client from `keeper === null`, because
             * those are different questions: a keeper who left their name
             * blank has still claimed the card, and offering it to the
             * next visitor would be offering something already taken.
             */
            keeperOffer: await keeperOffer(env, s, url.searchParams.get("editKey")),
          }
        : { active: false },
      { headers },
    );
  }

  // ── a duck's public page ────────────────────────────────────────────────
  // Checked before /api/duck/<editKey>: "by-slug" contains a hyphen and an
  // edit key cannot, so they can never collide, but order makes that
  // obvious rather than something you have to work out.
  if (path.startsWith("/api/duck/by-slug/") && req.method === "GET") {
    const duck = await duckBySlug(env, path.slice("/api/duck/by-slug/".length));
    if (!duck) return notFound(headers);
    // "Most bumps from" — free, now that bumps are per-pair.
    return json({ duck, bumpers: await topBumpers(env, duck.id) }, { headers });
  }

  if (path === "/api/slug/check" && req.method === "GET") {
    // Powers the "that one is taken" hint while someone types. It only
    // answers about the slug it was asked about, so it leaks nothing that
    // visiting /d/<slug> would not already reveal.
    const wanted = normaliseSlug(url.searchParams.get("s"));
    if (!wanted) return json({ ok: false, reason: "invalid" }, { headers });
    const taken = await slugTaken(env, wanted);
    return json({ ok: !taken, slug: wanted, reason: taken ? "taken" : null }, { headers });
  }

  if (path === "/api/slug" && req.method === "POST") {
    const body = await readJson(req);
    const editKey = typeof body?.editKey === "string" ? body.editKey : "";
    const result = await renameDuck(env, editKey, body?.slug);
    return result.ok
      ? json(result, { headers })
      : json(result, { status: result.reason === "taken" ? 409 : 400, headers });
  }

  // ── release ─────────────────────────────────────────────────────────────
  if (path === "/api/duck" && req.method === "POST") {
    const id = await readSessionCookie(env, req);
    const s = id ? await loadSession(env, id) : null;
    if (!s) return json({ error: "no session" }, { status: 401, headers });
    if (s.spentDuck) return json({ error: "already released" }, { status: 409, headers });

    const body = await readJson(req);
    if (!body) return badRequest("bad body", headers);

    // The fortune comes from the SESSION, never from the client — the
    // browser can ask for a duck, it cannot choose which fortune it got.
    const checked = validateDuck({ ...body, fortune: s.fortune } as DuckInput);
    if ("error" in checked) return badRequest(checked.error, headers);

    // Same cleaning as public text. A contact never renders in the pond,
    // but it does render in admin, and a UTF-16 slice can split a surrogate
    // pair and leave a broken character in the one field David has to
    // actually read.
    const value = cleanText(body.contact, 120);
    // No contact is how "shared with nobody" is spelled: no row, nothing to
    // leak, nothing to have to delete later.
    const contact = value ? { value, scope: validateScope(body.scope) } : null;

    const made = await createDuck(env, s.id, visitor, s.cardId, checked, contact);
    if ("error" in made) return json({ error: made.error }, { status: 409, headers });

    return json({ id: made.id, slug: made.slug, editKey: made.editKey },
      { status: 201, headers });
  }

  // ── bump ────────────────────────────────────────────────────────────────
  if (path === "/api/bump" && req.method === "POST") {
    const body = await readJson(req);
    const targetId = typeof body?.id === "string" ? body.id : "";
    if (!DUCK_ID.test(targetId)) return badRequest("bad id", headers);

    // The bumper proves it owns the duck doing the bumping. Without this,
    // anyone could spend a stranger's ten unreturned bumps for them — which
    // would turn the cap from a courtesy into a way to silence someone.
    const editKey = typeof body?.editKey === "string" ? body.editKey : "";
    const mine = await duckByEditKey(env, editKey);
    if (!mine) return json({ error: "make a duck to bump" }, { status: 403, headers });

    const result = await bump(env, mine.id, targetId);
    // `from` so the client can animate the right duck swimming over. It is
    // the caller's own duck — they just proved they own it — so this
    // discloses nothing they did not already send.
    if (result.ok) return json({ ...result, from: mine.id }, { headers });
    /*
     * `error` as well as `reason`, because that is the field `ApiError`
     * reads to build its message — and 409 covers two different answers
     * here. Without it the client saw a bare status and mapped BOTH the
     * ten-unreturned cap and a self-bump to "bump them back first", which
     * is advice that cannot be taken about a person who is you.
     */
    return result.reason === "unknown"
      ? notFound()
      : json({ ...result, error: result.reason }, { status: 409, headers });
  }

  if (path === "/api/say" && req.method === "POST") {
    const body = await readJson(req);
    const editKey = typeof body?.editKey === "string" ? body.editKey : "";
    const duck = await duckByEditKey(env, editKey);
    if (!duck) return json({ error: "unknown duck" }, { status: 403, headers });
    const result = await say(env, duck.id, body?.text);
    return result.ok
      ? json({ ok: true, text: result.text, cooldown: result.cooldown }, { headers })
      : json({ ok: false, retryAfter: result.retryAfter }, { status: 429, headers });
  }

  if (path.startsWith("/api/fire/") && path.endsWith("/out") && req.method === "POST") {
    const duckId = path.slice("/api/fire/".length, -"/out".length);
    if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);
    // Being late is not an error — animate the extinguish regardless.
    const r = await extinguish(env, duckId, visitor);
    return json({ ok: true, ...r }, { headers });
  }

  // ── report ──────────────────────────────────────────────────────────────
  if (path === "/api/report" && req.method === "POST") {
    const body = await readJson(req);
    const duckId = typeof body?.id === "string" ? body.id : "";
    if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);

    const result = await report(env, duckId, visitor, body?.reason, body?.note);
    if (!result.ok) {
      return result.reason === "unknown" ? notFound() : badRequest(result.reason);
    }
    // `filed: false` means this visitor had already reported it. That is the
    // same outcome as reporting it, and the button says "Reported ✓" either
    // way — there is nothing here worth turning into an error.
    return json(result, { headers });
  }

  // ── claiming a card ─────────────────────────────────────────────────────
  //
  // Reached by tapping a card that was armed with four blows. The claim is
  // in the URL the card wrote, so this is a POST the client makes on
  // arrival rather than something anyone types.
  if (path === "/api/claim" && req.method === "POST") {
    const body = await readJson(req);
    const card = safeToken(typeof body?.card === "string" ? body.card : null, 12);
    const counter = typeof body?.counter === "number" ? body.counter : NaN;
    const token = typeof body?.token === "string" ? body.token : "";
    if (!card || !Number.isInteger(counter)) return badRequest("bad claim", headers);

    const claim = await claimCard(
      env, card, counter, token,
      typeof body?.editKey === "string" ? body.editKey : null,
      body?.confirm === true,
    );
    if ("error" in claim) {
      // Every refusal looks the same from outside. Distinguishing "bad
      // token" from "already used" would tell somebody walking the counter
      // space exactly how close they were.
      return json({ ok: false }, { status: 403, headers });
    }

    /*
     * Not a refusal — a question. Somebody keeps this card and the person
     * holding it has not proved they are that somebody, so nothing has
     * been decided and the counter is unspent. 200, because the request
     * was fine; the answer is simply "ask them first".
     *
     * The keeper's name is disclosed, and that is deliberate: it is
     * already public on every duck from this card, and a takeover screen
     * that will not say whose card it is cannot be reasoned about by the
     * person about to take it.
     */
    if ("takeover" in claim) {
      return json({ ok: false, takeover: true, keeper: claim.keeper }, { headers });
    }

    /*
     * If this browser already has a duck from this card, that duck becomes
     * the keeper's — which is what gives them a durable way back once the
     * cookie below expires. Checked, not trusted: `linkClaimerDuck` only
     * accepts a duck THIS CARD minted.
     */
    await linkClaimerDuck(
      env, claim.epochId, card,
      typeof body?.editKey === "string" ? body.editKey : null,
    );

    // The epoch id IS the credential for Card setup, the same way an edit
    // key is for a duck. It goes in a cookie rather than the URL so it does
    // not end up in history or a Referer.
    headers.append("set-cookie", [
      `pond_keeper=${claim.epochId}`,
      "Path=/", "HttpOnly", "Secure", "SameSite=Lax", "Max-Age=3600",
    ].join("; "));
    return json({ ok: true, orphans: claim.orphans }, { headers });
  }

  /*
   * The other way to become a keeper: having just made a duck from a card
   * nobody keeps. No gesture, no instructions — see `claimFromSession` for
   * what is actually being proved and why `sessions.spent_duck` is the
   * thing that proves it.
   *
   * A POST with no body, because the request carries no information: the
   * session cookie IS the argument, and anything the client could send
   * would only be something to check rather than something to trust.
   */
  if (path === "/api/claim/first" && req.method === "POST") {
    const body = await readJson(req);
    const id = await readSessionCookie(env, req);
    const s = id ? await loadSession(env, id) : null;
    if (!s) return json({ ok: false }, { status: 401, headers });

    const claim = await claimFromSession(
      env, s, typeof body?.editKey === "string" ? body.editKey : null,
    );
    if ("error" in claim) {
      // "already kept" is the one refusal worth distinguishing: it is not
      // a failure, it is somebody else having got there, and the client
      // should take the offer down rather than retry it.
      const kept = claim.error === "already kept";
      return json({ ok: false, kept }, { status: kept ? 409 : 403, headers });
    }

    // Same credential as a four-blow claim, same shape, same reasons: a
    // cookie rather than a URL, so it stays out of history and Referer.
    headers.append("set-cookie", [
      `pond_keeper=${claim.epochId}`,
      "Path=/", "HttpOnly", "Secure", "SameSite=Lax", "Max-Age=3600",
    ].join("; "));
    return json({ ok: true, orphans: claim.orphans }, { headers });
  }

  /*
   * Hand the card on. Same two credentials as `/api/keeper`, because it is
   * the same authority — and a separate route rather than a flag on the
   * save, so that "I am no longer keeping this" can never be something a
   * save does by accident.
   */
  if (path === "/api/keeper/end" && req.method === "POST") {
    const body = await readJson(req);
    const cookie = (req.headers.get("cookie") ?? "").match(
      /(?:^|;\s*)pond_keeper=([A-Za-z0-9]{8,32})/,
    )?.[1];
    /*
     * `null` only when the field is absent. An empty string is a key that
     * resolves to nothing, and treating it as "no key given" let a live
     * cookie for another card answer — which is the same wrong-card
     * hazard the precedence below exists to close.
     */
    const key = typeof body?.editKey === "string" ? body.editKey : null;
    /*
     * ══ THE EXPLICIT CREDENTIAL WINS ══
     * The cookie used to be preferred, which is wrong whenever both are
     * present and they disagree. A keeper of card A still holding a live
     * `pond_keeper` cookie who opens the settings of a duck from card B
     * would post B's edit key and END A'S TENURE — a destructive action
     * on a card they were not looking at. Codex found the same
     * precedence on the read route.
     *
     * A key names one duck and therefore one card; a cookie is whatever
     * was claimed most recently in this browser. When the request says
     * which one it means, that is the answer.
     */
    /*
     * Explicit beats ambient, and an explicit credential that resolves to
     * nothing is a REFUSAL rather than a reason to fall back.
     *
     * `?? cookie` was not enough. The settings screen sends a key for
     * every duck, and most ducks are nobody's keeper duck — so with a
     * live `pond_keeper` for card A in the browser, opening a duck of
     * card B resolved to nothing, fell through to the cookie, and handed
     * on CARD A from card B's screen. That is the wrong-card destructive
     * action the previous fix was for, surviving through the other door.
     */
    const epochId = key !== null ? await epochForEditKey(env, key) : cookie;
    if (!epochId) return notFound(headers);

    const ended = await endTenure(env, epochId);
    if (!ended) return notFound(headers);
    // The cookie is spent the moment the tenure is. Leaving it set would
    // leave a dead credential in the browser that 404s confusingly.
    headers.append("set-cookie", [
      "pond_keeper=", "Path=/", "HttpOnly", "Secure", "SameSite=Lax", "Max-Age=0",
    ].join("; "));
    return json({ ok: true }, { headers });
  }

  if (path === "/api/keeper") {
    const cookie = (req.headers.get("cookie") ?? "").match(
      /(?:^|;\s*)pond_keeper=([A-Za-z0-9]{8,32})/,
    )?.[1];

    /*
     * Two credentials, and the cookie is only the fresher one. It lasts an
     * hour — right for the moment after a claim, hopeless as the only way
     * back — so a keeper may also present their own duck's private link,
     * which `epochForEditKey` resolves only while their tenure is current
     * and only for a duck the card itself minted.
     *
     * The body is read once and reused: a Request body is a stream and
     * consuming it twice yields nothing the second time.
     */
    const body = req.method === "POST" ? await readJson(req) : null;
    /*
     * ══ editKey MEANS TWO THINGS ON THIS ROUTE ══
     * On the GET it is purely a credential, so present-and-empty is an
     * unresolved one and must not fall back on whatever this browser
     * claimed last.
     *
     * On the POST it is ALSO a payload field: an empty string is how the
     * setup screen says "unlink my duck". Treating that as a failed
     * credential broke unlinking, which is authorised by the cookie and
     * always was.
     *
     * So the POST authorises on a NON-EMPTY key only. Nobody holds an
     * empty key, so this cannot be used to borrow another card's cookie:
     * the full setup screen is reached by claiming, which sets the cookie
     * for that same card.
     */
    const key = req.method === "POST"
      ? (typeof body?.editKey === "string" && body.editKey ? body.editKey : null)
      : url.searchParams.get("editKey");
    // Strict, for the reason spelled out on `/api/keeper/end` above: a
    // key that resolves to nothing means this duck keeps no card, and
    // answering with whatever the cookie remembers puts another card's
    // settings on this duck's screen.
    const epochId = key !== null ? await epochForEditKey(env, key) : cookie;
    if (!epochId) return notFound(headers);

    if (req.method === "GET") {
      const state = await keeperState(env, epochId);
      return state ? json(state, { headers }) : notFound(headers);
    }

    if (req.method === "POST") {
      const saved = await saveKeeper(env, epochId, body ?? {});
      return "error" in saved
        ? json(saved, { status: 403, headers })
        : json(saved, { headers });
    }
  }

  // ── /pondkeeper ─────────────────────────────────────────────────────────
  //
  // Everything under here is behind the password, and an unauthorised
  // request gets the SAME 404 an unknown route gets. An admin panel that
  // announces itself with a 401 is a thing to try passwords against.
  if (path.startsWith("/api/admin")) {
    if (path === "/api/admin/in" && req.method === "POST") {
      const body = await readJson(req);
      const cookie = await signIn(env, body?.password);
      if (!cookie) return notFound(headers);
      headers.append("set-cookie", cookie);
      return json({ ok: true }, { headers });
    }

    if (!(await authorised(req, env))) return notFound(headers);

    if (path === "/api/admin" && req.method === "GET") {
      const state = await adminState(env);
      // adminState builds its own response; copy the security headers on.
      const out = new Response(state.body, state);
      for (const [k, v] of headers) out.headers.append(k, v);
      return out;
    }

    if (path === "/api/admin/csv" && req.method === "GET") {
      const csv = contactsCsv(await adminDucks(env));
      headers.set("content-type", "text/csv; charset=utf-8");
      headers.set("content-disposition", 'attachment; filename="pond-contacts.csv"');
      return new Response(csv, { headers });
    }

    if (req.method === "POST") {
      const body = await readJson(req);

      /*
       * ── the cards, before the ducks ─────────────────────────────────
       * These are keyed by a card SERIAL, not a duck id, so they are
       * matched before the duck-id guard below rejects them for not
       * looking like one.
       */
      if (path.startsWith("/api/admin/card")) {
        const card = safeToken(typeof body?.card === "string" ? body.card : null, 12);
        if (!card) return badRequest("bad card", headers);

        if (path === "/api/admin/card/label") {
          const ok = await setCardLabel(env, card, String(body?.label ?? ""));
          return ok ? json({ ok: true }, { headers }) : notFound(headers);
        }
        if (path === "/api/admin/card/disabled") {
          const ok = await setCardDisabled(env, card, Boolean(body?.disabled));
          return ok ? json({ ok: true }, { headers }) : notFound(headers);
        }
        if (path === "/api/admin/card/keeper") {
          const res = await setKeeper(env, card, { name: body?.name, lang: body?.lang });
          if ("error" in res) {
            // The two refusals a person can act on, so they are told apart
            // rather than both becoming "something went wrong".
            return json({ ok: false, error: res.error }, { status: 409, headers });
          }
          return json({ ok: true }, { headers });
        }
        /*
         * Making a card new again. Three separate routes because they are
         * three separate consequences — see the note in admin.ts. Nothing
         * here deletes a duck; `/ducks/delete` below does, and is the only
         * one that asks twice.
         */
        if (path === "/api/admin/card/reset") {
          return json({ ok: await resetKeeper(env, card) }, { headers });
        }
        if (path === "/api/admin/card/unlink") {
          return json({ ok: true, unlinked: await unlinkDucks(env, card) }, { headers });
        }
        if (path === "/api/admin/card/attach") {
          const duckId = typeof body?.duck === "string" ? body.duck : "";
          if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);
          const res = await attachDuck(env, duckId, card);
          return "error" in res
            ? json({ ok: false, error: res.error }, { status: 409, headers })
            : json({ ok: true }, { headers });
        }
        if (path === "/api/admin/card/ducks/delete") {
          /*
           * Every duck from this card, through the ordinary delete so the
           * ducks_before_delete trigger fires and the contacts go with
           * them. The confirmation is the admin screen's job — it types
           * the card's label back — because a server that asks twice is a
           * server with a state machine in it.
           */
          return json(
            { ok: true, deleted: await deleteCardDucks(env, card) },
            { headers },
          );
        }
        if (path === "/api/admin/card/delete") {
          const res = await deleteCard(env, card);
          if ("error" in res) {
            return json({ ok: false, error: res.error }, { status: 409, headers });
          }
          return json({ ok: true }, { headers });
        }
        return notFound(headers);
      }

      if (path === "/api/admin/duck/delete") {
        const id = typeof body?.id === "string" ? body.id : "";
        if (!DUCK_ID.test(id)) return badRequest("bad id", headers);
        // Through the ordinary delete, so the trigger fires and the
        // contact goes with the duck. See the note in admin.ts.
        return json({ ok: await deleteDuckAsAdmin(env, id) }, { headers });
      }

      const duckId = typeof body?.id === "string" ? body.id : "";
      if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);

      if (path === "/api/admin/hide") {
        const ok = await setHidden(env, duckId, Boolean(body?.hidden));
        return ok ? json({ ok: true }, { headers }) : notFound(headers);
      }
      if (path === "/api/admin/replied" || path === "/api/admin/postcard") {
        const field = path.endsWith("replied") ? "replied" : "postcard";
        const ok = await markContact(env, duckId, field, Boolean(body?.done));
        return ok ? json({ ok: true }, { headers }) : notFound(headers);
      }
      if (path === "/api/admin/resolve") {
        return json({ resolved: await resolveReports(env, duckId) }, { headers });
      }
    }

    return notFound(headers);
  }

  /*
   * ── taking back a contact ───────────────────────────────────────────────
   * Before the block below, because that one reads the whole tail of the
   * path as an edit key and would take "<key>/contact" for a key of its
   * own — a 404 that looks like a wrong link rather than a missing route.
   *
   * DELETE and nothing else. There is no GET here on purpose: a contact is
   * never read back out, not even to the person who left it. See
   * `contact.ts`.
   */
  if (path.startsWith("/api/duck/") && path.endsWith("/contact")) {
    if (req.method !== "DELETE" && req.method !== "PUT") return notFound(headers);
    const editKey = path.slice("/api/duck/".length, -"/contact".length);
    // The key has to name a real duck, or withdrawing from a key somebody
    // guessed would report the same "nothing to take back" as withdrawing
    // from your own empty duck — and that answer is worth a probe.
    if (!(await duckByEditKey(env, editKey))) return notFound(headers);

    if (req.method === "PUT") {
      const body = await readJson(req);
      if (!body) return badRequest("bad body", headers);
      // The same cleaning the release gives it. A contact never renders in
      // the pond, but it is still text somebody typed.
      const value = cleanText(body.contact, 120);
      if (!value) return badRequest("no contact", headers);
      await setContact(env, editKey, value);
      /*
       * Identical whether this replaced one or was the first. Same
       * argument as the DELETE below: "was there already a contact here"
       * is the question this route exists to refuse.
       */
      return json({ ok: true }, { headers });
    }

    /*
     * ══ THE ANSWER IS THE SAME EITHER WAY ══
     * This used to return `removed`, so the copy could say "Gone" or
     * "there was nothing to take back". Reviewed and dropped: that
     * boolean is the same bit this route refuses to serve over GET, just
     * spent destructively. "Did this person leave their number" is a
     * smaller leak than the number and still one nobody agreed to, and
     * arguing that from the GET while shipping it in the DELETE is not an
     * argument, it is a loophole.
     *
     * The withdrawal still happens. Only the report of what was there
     * before it is gone, and one sentence covers both cases honestly:
     * after this, nobody can reply either way.
     */
    await withdrawContact(env, editKey);
    return json({ ok: true }, { headers });
  }

  // ── the owner's own duck ────────────────────────────────────────────────
  if (path.startsWith("/api/duck/")) {
    const editKey = path.slice("/api/duck/".length);
    const duck = await duckByEditKey(env, editKey);
    if (!duck) return notFound(headers);

    if (req.method === "GET") return json({ duck }, { headers });

    if (req.method === "PATCH") {
      const body = await readJson(req);
      if (!body) return badRequest("bad body", headers);
      const checked = validateDuck({ ...body, fortune: duck.fortune } as DuckInput);
      if ("error" in checked) return badRequest(checked.error, headers);
      const ok = await updateDuck(env, editKey, checked);
      return ok ? json({ ok: true }, { headers }) : notFound();
    }

    if (req.method === "DELETE") {
      // The contact goes with it, and so does everything else. One action.
      const ok = await deleteDuck(env, editKey);
      return ok ? json({ ok: true }, { headers }) : notFound();
    }
  }

  return notFound(headers);
}

/**
 * The daily cron, at 04:00. Sessions, nonces and spent rate-limit windows.
 *
 * Nothing time-sensitive lives here: fires ignite on read and go out by
 * arithmetic, so a sweep that runs late costs nothing.
 */
export async function scheduled(env: Env): Promise<void> {
  await sweep(env);
}
