/**
 * The Pond — the API router.
 *
 * Platform-agnostic on purpose: `handle(req, env)` takes a web `Request` and
 * returns a web `Response`, and knows nothing about Vercel. `api/` holds the
 * three-line files that hand it one. That is what made the move off
 * Cloudflare a day's work instead of a rewrite, and it is what would make
 * the next move the same.
 *
 * Two things are worth reading before changing anything here:
 *
 *  1. `?d=` is checked exactly once (see session.ts) and never again.
 *  2. `?d=` is also FORGEABLE — anyone can type /?d=1. It proves a fortune
 *     was requested, not that a coin was inserted. Everything that could be
 *     abused because of that is rate-limited per card and per visitor (see
 *     limits.ts), and the honest threat model is in docs/pond/SECURITY.md.
 *
 * Served from ducky.davidyang.work — its own subdomain, because the apex
 * davidyang.work stays on Cargo.
 */

import type { DuckInput } from "./ducks.js";
import {
  deleteDuck, duckByEditKey, duckBySlug, listPond, renameDuck,
  topBumpers, updateDuck, validateDuck, validateScope,
} from "./ducks.js";
import {
  adminDucks, adminState, authorised, contactsCsv, markContact,
  resolveReports, setHidden, signIn,
} from "./admin.js";
import { createDuck } from "./release.js";
import { normaliseSlug, slugTaken } from "./slug.js";
import { bump, extinguish, maybeIgnite, report, say } from "./social.js";
import { loadSession, mintSession, readSessionCookie, sweep, visitorHash } from "./session.js";
import type { Env } from "./types.js";
import { badRequest, cleanText, intParam, json, notFound, nowSec, randomId, safeToken } from "./util.js";

const VISITOR_COOKIE = "pond_v";

/** Internal duck ids, as generated by randomId(10). */
const DUCK_ID = /^[A-Za-z0-9]{6,16}$/;

/** Applied to every response. */
export function securityHeaders(extra?: HeadersInit): Headers {
  const h = new Headers(extra);
  h.set("x-content-type-options", "nosniff");
  h.set("x-frame-options", "DENY");
  // The edit link IS the credential, so it must never travel in a Referer
  // header to anything a duck's message happens to link to.
  h.set("referrer-policy", "no-referrer");
  h.set(
    "content-security-policy",
    "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; " +
      "script-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'self'; " +
      "frame-ancestors 'none'",
  );
  return h;
}

/**
 * A stable-per-browser id used only to count rescues and reports once per
 * person, and to rate-limit minting. Not an IP, not a fingerprint; if it's
 * cleared, the worst that happens is someone gets a fresh allowance.
 */
export async function ensureVisitor(
  req: Request,
  env: Env,
): Promise<{ visitor: string; setCookie: string | null }> {
  const cookies = req.headers.get("cookie") ?? "";
  const match = cookies.match(/(?:^|;\s*)pond_v=([A-Za-z0-9]{8,64})/);
  if (match?.[1]) return { visitor: await visitorHash(env, match[1]), setCookie: null };

  const raw = randomId(24);
  const setCookie = [
    `${VISITOR_COOKIE}=${raw}`,
    "Path=/",
    "HttpOnly",
    "Secure",
    "SameSite=Lax",
    "Max-Age=31536000",
  ].join("; ");
  return { visitor: await visitorHash(env, raw), setCookie };
}

async function readJson(req: Request): Promise<Record<string, unknown> | null> {
  if (!req.headers.get("content-type")?.includes("application/json")) return null;
  // A public write endpoint should not accept an unbounded body.
  const text = await req.text();
  if (text.length > 4096) return null;
  try {
    const parsed = JSON.parse(text);
    return typeof parsed === "object" && parsed !== null ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Exchange a fresh `?d=` for a session, if there is one to exchange.
 *
 * Lives here rather than in the shell renderer because both the pond page
 * and any future entry point need identical behaviour, and because getting
 * this wrong in one place only would be invisible until someone's duck
 * died on the submit button.
 */
export async function mintFromQuery(
  req: Request,
  env: Env,
  url: URL,
  visitor: string,
): Promise<string | null> {
  const digit = intParam(url.searchParams.get("d"), 0, 4);
  if (!digit || digit < 1) return null;

  // Already holding a live session: leave it alone. Re-tapping a card
  // mid-decoration must not hand out a second fortune and orphan the first.
  const existing = await readSessionCookie(env, req);
  if (existing && (await loadSession(env, existing))) return null;

  const minted = await mintSession(env, {
    digit,
    cardId: safeToken(url.searchParams.get("c"), 12),
    nonce: safeToken(url.searchParams.get("n"), 32),
    visitor,
  });
  return minted ? minted.cookie : null;
}

/**
 * Everything under /api.
 *
 * `pathname` is passed in rather than read off the request, because on
 * Vercel `/api/*` arrives through a rewrite and a rewritten request carries
 * its DESTINATION path, not the one the visitor typed. `api/router.ts`
 * reassembles the real one and hands it over; nothing in this file needs to
 * know that happened, which is the point of the split.
 *
 * It falls back to `req.url` so that tests, and any platform that routes by
 * path natively, can call this with two arguments and get the obvious
 * behaviour.
 */
export async function handle(req: Request, env: Env, pathname?: string): Promise<Response> {
  const url = new URL(req.url);
  const path = (pathname ?? url.pathname).replace(/\/+$/, "") || "/";

  const { visitor, setCookie } = await ensureVisitor(req, env);
  const headers = securityHeaders();
  if (setCookie) headers.append("set-cookie", setCookie);

  // ── the pond ────────────────────────────────────────────────────────────
  if (path === "/api/pond" && req.method === "GET") {
    // Ignition happens HERE, on read, not on a timer. Vercel Hobby crons
    // run daily and a finer expression fails at deploy — but a fire nobody
    // is present to see was never worth lighting, so this is the better
    // design rather than a workaround. See docs/pond/HOSTING.md § 2.
    await maybeIgnite(env);
    const ducks = await listPond(env);
    return json({ ducks, now: nowSec() }, { headers });
  }

  if (path === "/api/session" && req.method === "GET") {
    const id = await readSessionCookie(env, req);
    const s = id ? await loadSession(env, id) : null;
    return json(
      s ? { active: true, fortune: s.fortune, spent: Boolean(s.spentDuck) } : { active: false },
      { headers },
    );
  }

  // ── a duck's public page ────────────────────────────────────────────────
  // Checked before /api/duck/<editKey>: "by-slug" contains a hyphen and an
  // edit key cannot, so they can never collide, but order makes that
  // obvious rather than something you have to work out.
  if (path.startsWith("/api/duck/by-slug/") && req.method === "GET") {
    const duck = await duckBySlug(env, path.slice("/api/duck/by-slug/".length));
    if (!duck) return notFound(headers);
    // "Most bumps from" — free, now that bumps are per-pair.
    return json({ duck, bumpers: await topBumpers(env, duck.id) }, { headers });
  }

  if (path === "/api/slug/check" && req.method === "GET") {
    // Powers the "that one is taken" hint while someone types. It only
    // answers about the slug it was asked about, so it leaks nothing that
    // visiting /d/<slug> would not already reveal.
    const wanted = normaliseSlug(url.searchParams.get("s"));
    if (!wanted) return json({ ok: false, reason: "invalid" }, { headers });
    const taken = await slugTaken(env, wanted);
    return json({ ok: !taken, slug: wanted, reason: taken ? "taken" : null }, { headers });
  }

  if (path === "/api/slug" && req.method === "POST") {
    const body = await readJson(req);
    const editKey = typeof body?.editKey === "string" ? body.editKey : "";
    const result = await renameDuck(env, editKey, body?.slug);
    return result.ok
      ? json(result, { headers })
      : json(result, { status: result.reason === "taken" ? 409 : 400, headers });
  }

  // ── release ─────────────────────────────────────────────────────────────
  if (path === "/api/duck" && req.method === "POST") {
    const id = await readSessionCookie(env, req);
    const s = id ? await loadSession(env, id) : null;
    if (!s) return json({ error: "no session" }, { status: 401, headers });
    if (s.spentDuck) return json({ error: "already released" }, { status: 409, headers });

    const body = await readJson(req);
    if (!body) return badRequest("bad body", headers);

    // The fortune comes from the SESSION, never from the client — the
    // browser can ask for a duck, it cannot choose which fortune it got.
    const checked = validateDuck({ ...body, fortune: s.fortune } as DuckInput);
    if ("error" in checked) return badRequest(checked.error, headers);

    // Same cleaning as public text. A contact never renders in the pond,
    // but it does render in admin, and a UTF-16 slice can split a surrogate
    // pair and leave a broken character in the one field David has to
    // actually read.
    const value = cleanText(body.contact, 120);
    // No contact is how "shared with nobody" is spelled: no row, nothing to
    // leak, nothing to have to delete later.
    const contact = value ? { value, scope: validateScope(body.scope) } : null;

    const made = await createDuck(env, s.id, s.cardId, checked, contact);
    if ("error" in made) return json({ error: made.error }, { status: 409, headers });

    return json({ id: made.id, slug: made.slug, editKey: made.editKey },
      { status: 201, headers });
  }

  // ── bump ────────────────────────────────────────────────────────────────
  if (path === "/api/bump" && req.method === "POST") {
    const body = await readJson(req);
    const targetId = typeof body?.id === "string" ? body.id : "";
    if (!DUCK_ID.test(targetId)) return badRequest("bad id", headers);

    // The bumper proves it owns the duck doing the bumping. Without this,
    // anyone could spend a stranger's ten unreturned bumps for them — which
    // would turn the cap from a courtesy into a way to silence someone.
    const editKey = typeof body?.editKey === "string" ? body.editKey : "";
    const mine = await duckByEditKey(env, editKey);
    if (!mine) return json({ error: "make a duck to bump" }, { status: 403, headers });

    const result = await bump(env, mine.id, targetId);
    if (result.ok) return json(result, { headers });
    return result.reason === "unknown"
      ? notFound()
      : json(result, { status: 409, headers });
  }

  if (path === "/api/say" && req.method === "POST") {
    const body = await readJson(req);
    const editKey = typeof body?.editKey === "string" ? body.editKey : "";
    const duck = await duckByEditKey(env, editKey);
    if (!duck) return json({ error: "unknown duck" }, { status: 403, headers });
    const result = await say(env, duck.id, body?.text);
    return result.ok
      ? json({ ok: true, text: result.text }, { headers })
      : json({ ok: false, retryAfter: result.retryAfter }, { status: 429, headers });
  }

  if (path.startsWith("/api/fire/") && path.endsWith("/out") && req.method === "POST") {
    const duckId = path.slice("/api/fire/".length, -"/out".length);
    if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);
    // Being late is not an error — animate the extinguish regardless.
    const r = await extinguish(env, duckId, visitor);
    return json({ ok: true, ...r }, { headers });
  }

  // ── report ──────────────────────────────────────────────────────────────
  if (path === "/api/report" && req.method === "POST") {
    const body = await readJson(req);
    const duckId = typeof body?.id === "string" ? body.id : "";
    if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);

    const result = await report(env, duckId, visitor, body?.reason, body?.note);
    if (!result.ok) {
      return result.reason === "unknown" ? notFound() : badRequest(result.reason);
    }
    // `filed: false` means this visitor had already reported it. That is the
    // same outcome as reporting it, and the button says "Reported ✓" either
    // way — there is nothing here worth turning into an error.
    return json(result, { headers });
  }

  // ── /pondkeeper ─────────────────────────────────────────────────────────
  //
  // Everything under here is behind the password, and an unauthorised
  // request gets the SAME 404 an unknown route gets. An admin panel that
  // announces itself with a 401 is a thing to try passwords against.
  if (path.startsWith("/api/admin")) {
    if (path === "/api/admin/in" && req.method === "POST") {
      const body = await readJson(req);
      const cookie = await signIn(env, body?.password);
      if (!cookie) return notFound(headers);
      headers.append("set-cookie", cookie);
      return json({ ok: true }, { headers });
    }

    if (!(await authorised(req, env))) return notFound(headers);

    if (path === "/api/admin" && req.method === "GET") {
      const state = await adminState(env);
      // adminState builds its own response; copy the security headers on.
      const out = new Response(state.body, state);
      for (const [k, v] of headers) out.headers.append(k, v);
      return out;
    }

    if (path === "/api/admin/csv" && req.method === "GET") {
      const csv = contactsCsv(await adminDucks(env));
      headers.set("content-type", "text/csv; charset=utf-8");
      headers.set("content-disposition", 'attachment; filename="pond-contacts.csv"');
      return new Response(csv, { headers });
    }

    if (req.method === "POST") {
      const body = await readJson(req);
      const duckId = typeof body?.id === "string" ? body.id : "";
      if (!DUCK_ID.test(duckId)) return badRequest("bad id", headers);

      if (path === "/api/admin/hide") {
        const ok = await setHidden(env, duckId, Boolean(body?.hidden));
        return ok ? json({ ok: true }, { headers }) : notFound(headers);
      }
      if (path === "/api/admin/replied" || path === "/api/admin/postcard") {
        const field = path.endsWith("replied") ? "replied" : "postcard";
        const ok = await markContact(env, duckId, field, Boolean(body?.done));
        return ok ? json({ ok: true }, { headers }) : notFound(headers);
      }
      if (path === "/api/admin/resolve") {
        return json({ resolved: await resolveReports(env, duckId) }, { headers });
      }
    }

    return notFound(headers);
  }

  // ── the owner's own duck ────────────────────────────────────────────────
  if (path.startsWith("/api/duck/")) {
    const editKey = path.slice("/api/duck/".length);
    const duck = await duckByEditKey(env, editKey);
    if (!duck) return notFound(headers);

    if (req.method === "GET") return json({ duck }, { headers });

    if (req.method === "PATCH") {
      const body = await readJson(req);
      if (!body) return badRequest("bad body", headers);
      const checked = validateDuck({ ...body, fortune: duck.fortune } as DuckInput);
      if ("error" in checked) return badRequest(checked.error, headers);
      const ok = await updateDuck(env, editKey, checked);
      return ok ? json({ ok: true }, { headers }) : notFound();
    }

    if (req.method === "DELETE") {
      // The contact goes with it, and so does everything else. One action.
      const ok = await deleteDuck(env, editKey);
      return ok ? json({ ok: true }, { headers }) : notFound();
    }
  }

  return notFound(headers);
}

/**
 * The daily cron, at 04:00. Sessions, nonces and spent rate-limit windows.
 *
 * Nothing time-sensitive lives here: fires ignite on read and go out by
 * arithmetic, so a sweep that runs late costs nothing.
 */
export async function scheduled(env: Env): Promise<void> {
  await sweep(env);
}
