// ABOUTME: Bundles the browser clients into readable static files committed for deployment.
// ABOUTME: Generates both the personal pond and admin artifacts with an auditable build manifest.

/**
 * Bundle src/client/ into public/app.js.
 *
 * ══ WHY THE OUTPUT IS COMMITTED ══
 * There is deliberately no build step at deploy time — `public/` is served
 * verbatim by the CDN, HOSTING.md says so, and test/deploy-shape.test.ts
 * asserts it. The client logic still wants to live in tested TypeScript
 * modules, so the bundle is generated HERE, committed, and shipped as a
 * static file. Exactly the pattern card-identity.json already uses:
 * generated, committed, never hand-edited, regenerated by a script.
 *
 * ══ WHY THIS SCRIPT IS NOT CALLED `build` ══
 * `vercel link` reported: "Build Command: `npm run vercel-build` or `npm run
 * build`". Vercel's zero-config detection RUNS a script called `build` at
 * deploy time. Naming this one `build` would quietly reintroduce a deploy
 * build — the exact thing the no-build-step invariant exists to prevent —
 * and the failure would only show as a deploy that behaves differently from
 * local. It is `build:client`, and it must stay that way.
 *
 *   npm run build:client          bundle once
 *   npm run build:client -- watch rebuild on change
 */

import { build, context } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

const watch = process.argv.includes("watch");

/** Kept in step with the CSP in src/worker/index.ts: script-src 'self'. */
const options = {
  // Two bundles. The admin shares the DOM helpers and nothing else — it has
  // no water, no camera and no sprites, and making one reader download the
  // canvas engine to read a list of contacts would be silly.
  entryPoints: ["src/client/main.ts", "src/client/admin.ts"],
  outdir: "public",
  bundle: true,
  format: "esm",
  // The audience is a phone that just tapped a card, so this is the floor
  // for iOS Safari and Android Chrome of the last few years, and no lower —
  // transpiling further would cost bytes for browsers nobody is holding.
  target: ["es2022", "safari16", "chrome110"],
  // Not minified. The whole client is a few tens of kilobytes over a CDN,
  // and a person who taps a card and opens the inspector should be able to
  // read what it does. `view-source` is a feature of this project.
  minify: false,
  sourcemap: false,
  charset: "utf8",
  legalComments: "none",
  banner: {
    js: [
      "// ABOUTME: Generated browser client for the Pond experience. Do not edit directly.",
      "// ABOUTME: Built from src/client by tools/build-client.mjs and committed for deployment.",
      "//",
      "// GENERATED by tools/build-client.mjs from src/client/. Do not edit.",
      "//",
      "// Committed on purpose: public/ is served verbatim by the CDN and",
      "// nothing builds at deploy time. Run `npm run build:client` after",
      "// changing anything under src/client/.",
    ].join("\n"),
  },
};

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("watching src/client/ → public/");
} else {
  const result = await build({ ...options, metafile: true });
  for (const [file, out] of Object.entries(result.metafile.outputs)) {
    if (!file.endsWith(".js")) continue;
    console.log(`${file}  ${(out.bytes / 1024).toFixed(1)} kB  from ${Object.keys(out.inputs).length} modules`);
    // A bundle that quietly stops including a module shows up as a blank
    // screen on somebody's phone, not as a build error.
    if (out.bytes < 1024) {
      console.error(`${file} is suspiciously small — did its entry point import anything?`);
      process.exit(1);
    }
  }
  writeFileSync("public/.build.meta", JSON.stringify(result.metafile, null, 2));
}
