#!/usr/bin/env python3
"""Generate src/client/stickers.ts from the authored sticker data.

Sticker art is authored as plain ASCII pixel rows so it stays diffable and
hand-editable. This turns it into a typed module the client imports.

    python3 tools/gen-stickers.py
"""

import pathlib

# slot, rows, anchor-x, anchor-y, label
STICKERS = {
    # ── hats ── anchor sits on the crown of the head
    "tophat":  ("hat",  [".kkkkk.", ".kkkkk.", ".rrrrr.", "kkkkkkk"], 3, 3, "Top hat"),
    "cap":     ("hat",  ["..bbbb..", ".bbbbbb.", "bbbbbbbb", ".....bbb"], 3, 3, "Cap"),
    "beanie":  ("hat",  ["..gg..", ".gggg.", "gggggg", "wwwwww"], 3, 3, "Beanie"),
    "cowboy":  ("hat",  ["...nnn...", "..nnnnn..", ".nnnnnnn.", "nnnnnnnnn"], 4, 3, "Cowboy hat"),
    "crown":   ("hat",  ["y.y.y.y", "yyyyyyy", ".yyyyy."], 3, 2, "Crown"),
    "party":   ("hat",  ["..w..", "..p..", ".ppp.", ".ppp.", "ppppp"], 2, 4, "Party hat"),
    "wizard":  ("hat",  ["...y...", "...b...", "..bbb..", "..bbb..", ".bbbbb.", "bbbbbbb"], 3, 5, "Wizard hat"),
    "wreath":  ("hat",  ["p.y.p.y", "ggggggg"], 3, 1, "Flower crown"),
    "halo":    ("hat",  [".yyyy.", "y....y"], 2, 1, "Halo"),
    "bow":     ("hat",  ["pp...pp", "pppwppp", "pp...pp"], 3, 1, "Hair bow"),
    # ── face ── lands on the eye
    "shades":  ("face", ["kkkkk", ".kkk."], 1, 0, "Sunglasses"),
    "specs":   ("face", ["ssss", "s..s", "ssss"], 1, 1, "Glasses"),
    "patch":   ("face", ["kkkk", ".kk."], 1, 0, "Eyepatch"),
    "blush":   ("face", ["ppp", ".p."], 1, 0, "Blush"),
    "tache":   ("face", ["nn.nn", ".n.n."], 2, 0, "Moustache"),
    # ── neck ──
    "scarf":   ("neck", ["rrrrrrr", "rrrrrrr", "..rr...", "..rr..."], 3, 0, "Scarf"),
    "bowtie":  ("neck", ["rr.rr", "rrwrr", "rr.rr"], 2, 1, "Bow tie"),
    "chain":   ("neck", ["ssssss", "..yy.."], 2, 0, "Chain"),
    "collar":  ("neck", ["wwwwww", ".w..w."], 2, 0, "Collar"),
    # ── body ──
    "heart":   ("body", [".rr.rr.", "rrrrrrr", "rrrrrrr", ".rrrrr.", "..rrr..", "...r..."], 3, 2, "Heart"),
    "star":    ("body", ["..y..", "yyyyy", ".yyy.", "y...y"], 2, 1, "Star"),
    "spot":    ("body", [".nn.", "nnnn", "nnnn", ".nn."], 1, 1, "Spot"),
    "stripe":  ("body", ["wwwwww", "......", "wwwwww"], 2, 1, "Stripes"),
    "pocket":  ("body", ["bbbb", "b..b", "bbbb"], 1, 1, "Pocket"),
    # ── held ── hangs at the duck's side
    "handbag": ("held", ["..s..", ".s.s.", "nnnnn", "nyyyn", "nnnnn"], 2, 4, "Handbag"),
    "tote":    ("held", ["s...s", "s...s", "ppppp", "ppppp", "ppppp"], 2, 4, "Tote bag"),
    "basket":  ("held", ["..s..", ".s.s.", "nwnwn", "wnwnw", "nwnwn"], 2, 4, "Basket"),
    "satchel": ("held", ["sssss", "n...n", "nnnnn", "nyynn", "nnnnn"], 2, 4, "Satchel"),
    # ── float ── sits beside the duck
    "balloon": ("float", [".rrr.", "rrrrr", "rrrrr", ".rrr.", "..r..", "..s..", "..s.."], 2, 6, "Balloon"),
    "fish":    ("float", [".oo.", "oooo", ".oo."], 1, 1, "Fish"),
    "leaf":    ("float", [".gg", "ggg", "gg."], 1, 1, "Leaf"),
    "spark":   ("float", [".y.", "yyy", ".y."], 1, 1, "Sparkle"),
}

# Default drop point per slot. This is what makes "surprise me" sensible.
SLOT_ORIGIN = {
    "hat": (15, 2),
    "face": (15, 5),
    "neck": (13, 10),
    "body": (10, 15),
    "held": (7, 13),
    "float": (5, 7),
}

HEADER = '''/**
 * Sticker art — GENERATED by tools/gen-stickers.py. Do not edit by hand.
 *
 * 32 accessories in six slots. The slot is what lets "surprise me" put hats
 * on heads and bags at the duck's side rather than scattering things at
 * random, and it gives keyboard placement a sensible starting position.
 *
 * `ax`/`ay` is the cell inside the sprite that lands on the tap point.
 */

export type SlotName = "hat" | "face" | "neck" | "body" | "held" | "float";

export interface StickerDef {
  slot: SlotName;
  rows: string[];
  ax: number;
  ay: number;
  name: string;
}

export const STICKER_PALETTE = {
  k: "#2B2B24", w: "#FFFFFF", r: "#FF4B4B", y: "#FFCA00", b: "#3FB5D8",
  g: "#5AD08A", p: "#FF6FA5", o: "#FF8953", n: "#8B5E34", s: "#C9D6DC",
} as const;

export const STICKERS: Record<string, StickerDef> = {
'''


def main() -> None:
    for key, (_slot, rows, ax, ay, _name) in STICKERS.items():
        width = len(rows[0])
        assert all(len(r) == width for r in rows), f"{key}: ragged rows"
        assert 0 <= ax < width and 0 <= ay < len(rows), f"{key}: anchor outside sprite"
        for row in rows:
            for ch in row:
                assert ch == "." or ch in "kwrybgpons", f"{key}: unknown colour {ch!r}"

    out = [HEADER]
    for key, (slot, rows, ax, ay, name) in STICKERS.items():
        body = ", ".join(f'"{r}"' for r in rows)
        out.append(f'  {key}: {{ slot: "{slot}", ax: {ax}, ay: {ay}, name: "{name}",')
        out.append(f"    rows: [{body}] }},")
    out.append("};")
    out.append("")
    out.append("/** Where a sticker lands by default: hats on the head, bags at the side. */")
    out.append("export const SLOT_ORIGIN: Record<SlotName, [number, number]> = {")
    for slot, (x, y) in SLOT_ORIGIN.items():
        out.append(f"  {slot}: [{x}, {y}],")
    out.append("};")
    out.append("")
    out.append("export const SLOT_LABELS: Record<SlotName, string> = {")
    out.append('  hat: "Hats", face: "Face", neck: "Neck",')
    out.append('  body: "Body", held: "Bags", float: "Extras",')
    out.append("};")
    out.append("")
    out.append("/** Six is the cap. They may overlap freely — that's part of the fun. */")
    out.append("export const MAX_STICKERS = 6;")
    out.append("")

    dest = pathlib.Path(__file__).resolve().parent.parent / "src" / "client" / "stickers.ts"
    dest.write_text("\n".join(out))
    print(f"wrote {dest.relative_to(dest.parent.parent.parent)} — {len(STICKERS)} stickers")


if __name__ == "__main__":
    main()
